/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kakaw;

import javax.swing.JOptionPane;
import java.sql.CallableStatement;
/**
 *
 * @author josec
 */
public class Crear_Tarjeta extends javax.swing.JFrame {

 

    /**
     * Creates new form Crear_Tarjeta
     */
    public Crear_Tarjeta() {
        initComponents();
    }
        
 public void Ingresar_Tarjeta(String numeroTar, String numeroSeg, String nombreUs, String compañia, String correo,String banco,String fecha,String tipo){
        try{
            procedimiento = Conexion.getInstancia().getConexion().prepareCall("CALL sp_Agregar_Tarjeta(?,?,?,?,?,?,?,?)");
            procedimiento.setString("_Numero_de_Tarjeta", numeroTar);
            procedimiento.setString("_Numero_de_Seguridad", numeroSeg);
            procedimiento.setString("_Nombre_Usuario", nombreUs);
            procedimiento.setString("_Compañia", compañia);
            procedimiento.setString("_Correo_Electronico",correo);
            procedimiento.setString("_Banco", banco);
            procedimiento.setString("_Fecha_de_vencimiento",fecha);
            procedimiento.setString("_Tipo_de_Tarjeta",tipo);
            
            procedimiento.executeQuery();

        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
 private static Tarjetas n = new Tarjetas();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fecha_Vencimiento = new javax.swing.JPanel();
        Numero_Tarjeta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Banco = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Numero_Seguridad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Compañia = new javax.swing.JComboBox<>();
        Crear_Nueva_Tarjeta = new javax.swing.JButton();
        Cancelar_Creacion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Fecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Tipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fecha_Vencimiento.setBackground(new java.awt.Color(0, 28, 76));

        Numero_Tarjeta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Numero_Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_TarjetaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero de Tarjeta");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Compañia");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Banco");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero Seguridad");

        Banco.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Banco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BancoActionPerformed(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Numero_Seguridad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nueva Tarjeta");

        Compañia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Compañia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opciones", "Visa", "Master Card", "American Express" }));

        Crear_Nueva_Tarjeta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Crear_Nueva_Tarjeta.setText("Crear");
        Crear_Nueva_Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_Nueva_TarjetaActionPerformed(evt);
            }
        });

        Cancelar_Creacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cancelar_Creacion.setText("Cancelar");
        Cancelar_Creacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_CreacionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha Vencimiento");

        Fecha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FechaMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de Tarjeta");

        Tipo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TipoMouseClicked(evt);
            }
        });
        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fecha_VencimientoLayout = new javax.swing.GroupLayout(Fecha_Vencimiento);
        Fecha_Vencimiento.setLayout(Fecha_VencimientoLayout);
        Fecha_VencimientoLayout.setHorizontalGroup(
            Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fecha_VencimientoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Crear_Nueva_Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancelar_Creacion)
                .addGap(33, 33, 33))
            .addGroup(Fecha_VencimientoLayout.createSequentialGroup()
                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fecha_VencimientoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Fecha_VencimientoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Numero_Tarjeta))
                            .addGroup(Fecha_VencimientoLayout.createSequentialGroup()
                                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(12, 12, 12)
                                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Numero_Seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Banco, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Compañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(Fecha_VencimientoLayout.createSequentialGroup()
                                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Fecha_VencimientoLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel7)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Fecha_VencimientoLayout.setVerticalGroup(
            Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fecha_VencimientoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero_Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Compañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero_Seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Fecha_VencimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Crear_Nueva_Tarjeta)
                    .addComponent(Cancelar_Creacion))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fecha_Vencimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fecha_Vencimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Numero_TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_TarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Numero_TarjetaActionPerformed

    private void BancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BancoActionPerformed

    private void Crear_Nueva_TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_Nueva_TarjetaActionPerformed
        String comp=(String) Compañia.getSelectedItem();
        
        if(Numero_Tarjeta.getText().isEmpty()==false && Compañia.getSelectedItem()!="Opciones"  && Banco.getText().isEmpty()==false && Nombre.getText().isEmpty()==false && Numero_Seguridad.getText().isEmpty()==false && Tipo.getText().isEmpty()==false && Fecha.getText().isEmpty()==false){
            if(validarNumeros(Numero_Tarjeta.getText())==true && validarNumeros(Numero_Seguridad.getText())==true){
                if(validarTarjeta()==true && validarSeguridad()==true){
                    Ingresar_Tarjeta(Numero_Tarjeta.getText(),Numero_Seguridad.getText(),Nombre.getText(),comp,correo,Banco.getText(),Fecha.getText(),Tipo.getText());
                    vaciarCajas();
                    n.llenarMapa();
                    Tarjetas.llenarTabla();
                   
                }else{
                     JOptionPane.showMessageDialog(null, "El número de tarjeta debe de tener 16 digitos.");
                }
               }else{
                JOptionPane.showMessageDialog(null,"Verifique que el numero de tarjeta y el numero de seguridad sean datos numericos.");
            }
        
        }else{
            JOptionPane.showMessageDialog(null,"Verifique que todas las cajas de texto se encuentren llenas.");
        }
                         dispose();
            Tarjetas s=new Tarjetas();
                s.setLocationRelativeTo(null);
                s.setDefaultCloseOperation(EXIT_ON_CLOSE);
                s.setResizable(false);
                s.setVisible(true);        

   
    
    }//GEN-LAST:event_Crear_Nueva_TarjetaActionPerformed

    private void FechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FechaMouseClicked
             
        
    }//GEN-LAST:event_FechaMouseClicked

    private void TipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoMouseClicked

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed

    private void Cancelar_CreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_CreacionActionPerformed
   dispose();
               Tarjetas s=new Tarjetas();
                s.setLocationRelativeTo(null);
                s.setDefaultCloseOperation(EXIT_ON_CLOSE);
                s.setResizable(false);
                s.setVisible(true);  
    }//GEN-LAST:event_Cancelar_CreacionActionPerformed
   private static boolean validarNumeros(String cadena){
    	try {
                Long.parseLong(cadena);
                return true;
    	} catch (NumberFormatException e){
               return false;
    	}
    }
   
    private  boolean validarTarjeta(){
        if(Numero_Tarjeta.getText().length()==16){
            return true;
        }else{
            return false;
        }  
    }
        private  boolean validarSeguridad(){
        if(Numero_Seguridad.getText().length()==3){
            return true;
        }else{
            return false;
        }  
    }
    private void vaciarCajas(){
        Numero_Tarjeta.setText("");
        Numero_Seguridad.setText("");
        Compañia.setSelectedItem("Opciones");
        Banco.setText("");
        Nombre.setText("");
        Fecha.setText("");
        Tipo.setText("");
 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Tarjeta().setVisible(true);
            }
        });
    }
    private CallableStatement procedimiento;
    private String correo= Ingreso.correo.getText();
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Banco;
    private javax.swing.JButton Cancelar_Creacion;
    private javax.swing.JComboBox<String> Compañia;
    private javax.swing.JButton Crear_Nueva_Tarjeta;
    private javax.swing.JTextField Fecha;
    private javax.swing.JPanel Fecha_Vencimiento;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Numero_Seguridad;
    private javax.swing.JTextField Numero_Tarjeta;
    private javax.swing.JTextField Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
